# Generated by Django 2.1.3 on 2018-11-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penndjangosaml2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longgroupname',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
